# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :bump_major do
    flutter_version_manager(
      arguments: "-major",
      yml: "./version.yml",
      pubspec: "./example_pubspec.yaml")
  end
  lane :bump_minor do
     flutter_version_manager(
      arguments: "-minor",
      yml: "./version.yml",
      pubspec: "./example_pubspec.yaml")
    end

  lane :bump_patch do
    flutter_version_manager(
      arguments: "-patch",
      yml: "./version.yml",
      pubspec: "./example_pubspec.yaml")
  end

  lane :read_version do
    flutter_version_manager(
      arguments: "-version",
      yml: "./version.yml",
      pubspec: "./example_pubspec.yaml")
  end

  lane :read_code do
    flutter_version_manager(
      arguments: "-code",
      yml: "./version.yml",
      pubspec: "./example_pubspec.yaml")
  end

  lane :apply_new_version do
    flutter_version_manager(
      arguments: "-apply",
      yml: "./version.yml",
      pubspec: "./example_pubspec.yaml")
  end


  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
#     gradle(task: "clean assembleRelease")
    changelog_from_git_commits
    upload_to_play_store(track: 'beta')
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
#     gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
